[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/icons/:library/:name.svg"
  to = "/.netlify/functions/icon-svg/:library/:name"
  status = 200
  force = true

[[redirects]]
  from = "/icons/:library/:name.png"
  to = "/.netlify/functions/icon-png/:library/:name"
  status = 200
  force = true

[[redirects]]
  from = "/plugin.json"
  to = "/.netlify/functions/plugin-config"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
